language: python
sudo: false
cache: pip
install: pip install tox-travis
script: tox
matrix:
  fast_finish: true
  include:
    - python: "3.8"
    - python: "3.7"
    - python: "3.6"
    - python: "3.5"
    - python: "3.4"
    - python: "2.7"
